name: smart_library_system
description: A smart library management system with real-time sensor monitoring

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  http: ^1.1.0
  provider: ^6.0.5
  fl_chart: ^0.65.0
  intl: ^0.18.1
  shared_preferences: ^2.2.1
  path_provider: ^2.1.1
  csv: ^5.0.2
  mqtt_client: ^10.0.0
  camera: ^0.10.5+5
  permission_handler: ^11.0.1
  flutter_local_notifications: ^16.1.0
  connectivity_plus: ^5.0.1
  google_fonts: ^6.1.0
  screenshot: ^2.1.0  # Use the latest version (Check at pub.dev)


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true